# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0876f532789323be0421a949e3eda8b09aef6b9ce1037f9aebc3166b904c7b13437b43e9293e99bc1d3d98d0bd7cfb1f5561dbe96095a07b00bd0c962274b225

test:
  secret_key_base: 443f10feb307b2d3d1c3e335ea7b9730d0f596fc787fb41f7e19bdcd13ffee3ee0e3451d65ade4a1893d6bf0c1a764b6027fc66db80dcc437f787fc2bf2afdcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
